### ISSUE TITLE
Roadmap : Sprint 1

### ISSUE THREAD

**Issue by telaoumatenyanis** [telaoumatenyanis/PerCEPtion-v2#1]
- [ ] replace lib folder with maven
- [ ] CI/CD, quality (Travis, SonarCloud, ..)
- [ ] Timestamp on events
- [ ] Proper resources simulation (threads ?)
